export const songs = [
  {
    album: "The All-American Rejects",
    duration: 228,
    title: "My Paper Heart",
    id: 0,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 260,
    title: "Your Star",
    id: 1,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 233,
    title: "Swing, Swing",
    id: 2,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 210,
    title: "Time Stands Still",
    id: 3,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 183,
    title: "One More Sad Song",
    id: 4,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 256,
    title: "Why Worry",
    id: 5,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 208,
    title: "Don't Leave Me",
    id: 6,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 245,
    title: "Too Far Gone",
    id: 7,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 180,
    title: "Drive Away",
    id: 8,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 260,
    title: "Happy Endings",
    id: 9,
    artist: "The All-American Rejects",
  },
  {
    album: "The All-American Rejects",
    duration: 300,
    title: "The Last Song",
    id: 10,
    artist: "The All-American Rejects",
  },
  {
    album: "Andy Grammer",
    duration: 190,
    title: "Keep Your Head Up",
    id: 11,
    artist: "Andy Grammer",
  },
  {
    album: "Funeral",
    duration: 288,
    title: "Neighborhood #1 (Tunnels)",
    id: 12,
    artist: "Arcade Fire",
  },
  {
    album: "Funeral",
    duration: 212,
    title: "Neighborhood #2 (Laika)",
    id: 13,
    artist: "Arcade Fire",
  },
  {
    album: "Funeral",
    duration: 221,
    title: "Une Année Sans Lumiere",
    id: 14,
    artist: "Arcade Fire",
  },
  {
    album: "Funeral",
    duration: 312,
    title: "Neighbourhood #3 (Power Out)",
    id: 15,
    artist: "Arcade Fire",
  },
  {
    album: "Funeral",
    duration: 289,
    title: "Neighborhood #4 (Kettles)",
    id: 16,
    artist: "Arcade Fire",
  },
];

export const getLibrary = () => songs;
